# Generated by Django 3.1.2 on 2020-10-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hospital_Name', models.CharField(max_length=50)),
                ('Mobile_Number', models.IntegerField()),
                ('User_Name', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Registerform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Mobile_Number', models.IntegerField()),
                ('Adhar_Number', models.IntegerField()),
                ('Date_Of_Birth', models.DateTimeField()),
                ('Sex', models.CharField(max_length=10)),
                ('Hospital_Name', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=10)),
                ('Slot_Booking_Date', models.DateTimeField(auto_now=True)),
                ('Doctor_Appointment_Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='superuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Supeer_User_Name', models.CharField(max_length=20)),
                ('Supeer_Password', models.CharField(max_length=20)),
            ],
        ),
    ]
