# Generated by Django 3.1.2 on 2020-10-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201023_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerform',
            name='Doctor_Appointment_Date',
        ),
        migrations.AlterField(
            model_name='registerform',
            name='Slot_Booking_Date',
            field=models.DateTimeField(),
        ),
    ]
