# Generated by Django 3.1.2 on 2020-10-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20201026_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerform',
            name='Address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registerform',
            name='Doctor_Appointment_Date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='registerform',
            name='Hospital_Name',
            field=models.CharField(max_length=100),
        ),
    ]
