# Generated by Django 3.1.5 on 2021-01-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20201107_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerforms',
            name='Doctor_Appointment_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
