# Generated by Django 3.1.5 on 2021-02-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210128_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerforms',
            name='Date_Of_Birth',
            field=models.DateField(),
        ),
    ]
