# Generated by Django 3.1.5 on 2021-02-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210204_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerforms',
            name='Doctor_Appointment_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
