# Generated by Django 3.1.5 on 2021-03-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210204_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerforms',
            name='Doctor_Appointment_Date',
        ),
        migrations.RemoveField(
            model_name='registerforms',
            name='Slot_Booking_Date',
        ),
    ]
