# Generated by Django 3.1.5 on 2021-03-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210310_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerforms',
            name='Doctor_Appointment_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registerforms',
            name='Slot_Booking_Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
