# Generated by Django 3.1.5 on 2021-03-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210310_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='superuser',
        ),
    ]
