# Generated by Django 3.1.5 on 2021-03-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_delete_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerforms',
            name='Adhar_Number',
            field=models.CharField(max_length=20),
        ),
    ]
