# Generated by Django 3.1.5 on 2021-03-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20210313_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='User_Name',
            field=models.IntegerField(),
        ),
    ]
