# Generated by Django 3.1.5 on 2021-03-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210313_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='superusers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.IntegerField()),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
